# Site settings
title: Web
description: Homepage for Lab X
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yinghui HUANG
user_description: Dreamer and Pragmatist.
user_title: Master degree candidate
email: erinhyh@foxmail.com
#twitter_username: YingHuiH
github_username:  YingHuiH
#gplus_username:  YingHuiH

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
