# Site settings
title: Web
description: Lab of Data Science and Intelligence
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: XXXXXXX
user_description: XXXXXXX
user_title: XXXXX

github_username:  XXXXXXX

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules','README.md']
